services:
  - type: web
    name: ecclesia-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        value: monSecretTemporaire123!